### ISSUE TITLE
Plugin suggestion

### ISSUE THREAD

**Issue by lynrayy** [MelnCat/LimitlessTps#2]
I don't know how to contact that's why im writing it here

Can you make plugin to make digging sound global? I mean when you in digging process, other player can't hear this sound. They hear only when block break. I've heard by my own ears on one server removed sound limitation and i think every server needs this plugin

**Comment by MelnCat** [comment]
what

**Comment by lynrayy** [comment]
I want someone to make this plugin

**Comment by lynrayy** [comment]
I see that you can change core server mechanics, that's why i suggest it to you

**Comment by lynrayy** [comment]
Wow what

**Comment by lynrayy** [comment]
Where can i found it?
