### ISSUE TITLE
What hosting are you using?

### ISSUE THREAD

**Issue by Developed7** [MelnCat/LimitlessTps#3]
![image](https://github.com/user-attachments/assets/4f897a5b-60fc-43ca-8475-e150be2747e9)
In the image for banner for https://modrinth.com/plugin/limitless-tps/gallery on modrinth what hosting are you using there.

**Comment by MelnCat** [comment]
It was a private one, if I remember right.

**Comment by Developed7** [comment]
> It was a private one, if I remember right.

Would you happen to remember the name of it or the panel it was using?
